import os

blog_dir = '/mnt/c/Users/spin_LKY_flex/adsense/src/content/blog'

kr_to_en = {
    '2026-earned-income-tax-credit': {
        'title': '2026 Korea Earned Income Tax Credit (EITC) & Child Tax Credit: Eligibility and Cash Payouts',
        'desc': 'Complete guide to Koreas Earned Income Tax Credit (EITC) and Child Tax Credit. Income criteria for single, single-income, and dual-income households, payment schedule, and NTS application.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['EITC', 'KoreaTaxCredit', 'ChildSupport', 'Hometax', 'WelfareKorea'],
        'intro': 'The Earned Income Tax Credit (EITC) and Child Tax Credit operated by the National Tax Service (NTS) provide direct cash support to low- and middle-income working households in Korea.',
        'c1_title': 'EITC Maximum Annual Cash Payouts',
        'c1_left': 'Single Households: Up to 1.65M KRW (Income < 22M KRW)',
        'c1_right': 'Dual-Income Households: Up to 3.30M KRW (Income < 44M KRW) + 1M KRW per child',
    },
    '2026-youth-monthly-rent-support': {
        'title': '2026 Korea Youth Monthly Rent Support: Up to 2.4 Million KRW Housing Subsidy',
        'desc': 'South Koreas Ministry of Land, Infrastructure and Transport (MOLIT) Youth Rent Subsidy. 200,000 KRW per month for 12 months, income/asset eligibility, and Bokjiro application.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['YouthRentSupport', 'KoreaHousingSubsidy', 'Bokjiro', 'ExpatLiving', 'SeoulRent'],
        'intro': 'For young individuals and students living independently in Korea, paying 500,000 to 700,000 KRW in monthly rent is a major fixed expense. The government provides 200,000 KRW monthly cash support for up to 12 months.',
        'c1_title': 'Youth Rent Subsidy 3 Key Requirements',
        'c1_left': 'Age & Housing: Age 19-34 living independently, deposit <= 50M KRW & rent <= 700K KRW',
        'c1_right': 'Income: Individual median income <= 60% (approx. 1.45M KRW/month)',
    },
    'auto-acquisition-tax-reduction-2026': {
        'title': '2026 Korea Vehicle Acquisition Tax Reductions: EV, Hybrid, and Multi-Child Family Benefits',
        'desc': 'Complete guide to Korean car acquisition tax exemptions. Electric vehicles (up to 1.4M KRW reduction), compact cars (500K KRW deduction), and multi-child family discounts.',
        'category': 'tax',
        'catName': 'Tax & Expat Settlement',
        'tags': ['CarTaxKorea', 'EVReduction', 'VehicleTax', 'Wetax', 'FamilyTax'],
        'intro': 'When purchasing a car in South Korea, standard non-commercial passenger vehicles incur a 7% acquisition tax. Taking advantage of statutory exemptions can save you millions of KRW.',
        'c1_title': 'Vehicle Tax Exemption Brackets',
        'c1_left': 'Electric Vehicles (EV) & FCEV: Up to 1,400,000 KRW tax exemption directly deducted',
        'c1_right': 'Multi-Child Families (3+ kids): 100% full tax exemption on 7-seater vehicles',
    },
    'best-parking-accounts-cma-2026': {
        'title': '2026 Best High-Yield Parking Accounts & CMA Accounts in Korea: Daily Compound Interest',
        'desc': 'Top high-yield parking accounts and CMA accounts in Korea. Kbank Plus Box, Toss Bank, KakaoBank Safe Box, and Brokerage RP-type CMAs for emergency funds.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['ParkingAccounts', 'CMAKorea', 'HighYieldSavings', 'TossBank', 'Kbank'],
        'intro': 'Leaving your emergency cash in standard 0.1% bank accounts costs you money. Parking accounts and CMAs in Korea pay 2.0% to 3.0%+ annual interest calculated daily.',
        'c1_title': 'Top Parking Account Features',
        'c1_left': 'Internet Banks (Kbank/Toss): 2.3%~2.5% daily compound interest with zero transfer fees',
        'c1_right': 'Brokerage CMAs (RP/MMW): Instant liquidity and high yield for investment-ready capital',
    },
    'credit-vs-check-card-tax-ratio': {
        'title': 'Korean Credit Card vs. Debit Card Tax Deduction Golden Ratio Formula',
        'desc': 'How to optimize your credit card (15%) and check card (30%) spending ratio to maximize year-end tax refunds in Korea. 25% salary threshold calculation guide.',
        'category': 'tax',
        'catName': 'Tax & Expat Settlement',
        'tags': ['CreditCardTax', 'CheckCardKorea', 'YearEndTax', 'TaxDeduction', 'SmartSpending'],
        'intro': 'Card spending tax deduction only triggers after you spend 25% of your annual salary. Knowing when to switch from credit cards to debit cards saves hundreds of thousands of KRW.',
        'c1_title': 'Card Spending Golden Ratio',
        'c1_left': '0% ~ 25% of Annual Salary: Use credit cards for points, cashback, and perks',
        'c1_right': 'Above 25% Threshold: Switch to debit cards (check cards) for double the deduction rate (30%)',
    },
    'family-loan-agreement-gift-tax': {
        'title': 'Family Loan Agreements (차용증) in Korea: How to Borrow 217 Million KRW Tax-Free',
        'desc': 'Legal guide to lending money between parents and children without gift tax in Korea. 4.6% statutory interest rate rule, 10M KRW annual interest threshold, and notarization.',
        'category': 'tax',
        'catName': 'Tax & Expat Settlement',
        'tags': ['FamilyLoan', 'GiftTaxKorea', 'LoanAgreement', 'Notarization', 'NTSAudit'],
        'intro': 'Transferring large sums between family members in Korea can trigger a 10% to 50% gift tax audit unless formal loan documentation (차용증) and interest payments are executed.',
        'c1_title': 'Legal 217M KRW Zero-Interest Rule',
        'c1_left': 'Statutory Interest (4.6%): Under 217M KRW, annual interest is below 10M KRW threshold',
        'c1_right': 'Audit Defense: Bank wire records, principal repayment schedule, and fixed-date notarization',
    },
    'find-hidden-insurance-dormant-accounts': {
        'title': 'How to Find Unclaimed Insurance Money & Dormant Bank Accounts in Korea (Account Info)',
        'desc': 'Step-by-step guide to recovering forgotten bank deposits, dormant insurance claims, and card points in Korea using Account Info (어카운트인포) and Nae Insurance Damoa.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['UnclaimedMoney', 'AccountInfo', 'DormantAccounts', 'KoreaBanking', 'InsuranceRefund'],
        'intro': 'Over 2 trillion KRW in unclaimed insurance dividends and dormant bank accounts are waiting to be claimed by residents in South Korea.',
        'c1_title': 'One-Stop Unclaimed Asset Portals',
        'c1_left': 'Account Info (payinfo.or.kr): View all active/dormant bank accounts and card points',
        'c1_right': 'Nae Insurance Damoa: Check all maturity, dividend, and unpaid insurance payouts instantly',
    },
    'freelancer-comprehensive-income-tax': {
        'title': 'Freelancer & 3.3% Withholding Tax Guide in Korea: May Global Income Tax Filing',
        'desc': 'Complete guide for freelancers, gig workers, and contractors with 3.3% withholding tax in South Korea. D/F type book-keeping, deductible business expenses, and HomeTax filing.',
        'category': 'tax',
        'catName': 'Tax & Expat Settlement',
        'tags': ['FreelancerTax', 'GlobalIncomeTax', '3.3PercentTax', 'HometaxFiling', 'NTSKorea'],
        'intro': 'Freelancers, instructors, and online creators in Korea who have 3.3% tax withheld must file their Global Income Tax Return (종합소득세) every May to claim massive refunds.',
        'c1_title': 'Filing Types & Expense Rates',
        'c1_left': 'Simple Expense Rate (F/G types): High automatic deduction percentage for beginner income',
        'c1_right': 'Standard Double-Entry Bookkeeping: Crucial for higher earners to deduct laptops, rent, transport',
    },
    'gold-investment-tax-comparison-2026': {
        'title': 'Gold Investment in Korea: KRX Spot Gold vs. Gold ETF vs. Bank Gold Accounts (0% Tax Guide)',
        'desc': 'Comparing 4 gold investment methods in South Korea. Why KRX Spot Gold offers 0% capital gains tax and no 15.4% dividend tax compared to bank gold accounts and ETFs.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['GoldInvestment', 'KRXGold', 'TaxFreeGold', 'GoldETF', 'SafeHavenAsset'],
        'intro': 'Gold is the premier safe-haven asset during inflation and currency swings. In Korea, choosing the right method means paying 0% tax vs. 15.4% dividend tax.',
        'c1_title': 'Gold Tax Comparison',
        'c1_left': 'KRX Spot Gold Market: 0% capital gains tax, no 15.4% dividend tax, 1g trading unit',
        'c1_right': 'Bank Gold Accounts & ETFs: 15.4% dividend tax applied on all capital gains',
    },
    'health-insurance-ceiling-refund-2026': {
        'title': 'Korean National Health Insurance (NHIS) Medical Copayment Refunds: 1.35M KRW Average Refund',
        'desc': 'How Korean residents and foreign subscribers can claim cash refunds on high annual medical expenses through the statutory NHIS copayment ceiling refund program.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['NHISRefund', 'KoreaMedicalCare', 'HealthInsurance', 'HospitalRefund', 'WelfareSupport'],
        'intro': 'If your annual covered out-of-pocket medical bills exceed your income bracket ceiling, the NHIS automatically refunds 100% of the excess amount back to your bank account.',
        'c1_title': 'NHIS Out-of-Pocket Ceilings',
        'c1_left': 'Lower Income Brackets: Annual hospital copay cap from 870K to 1.62M KRW',
        'c1_right': 'Overpayment Refund: Excess cash transferred directly to registered bank account within 48 hours',
    },
    'housing-rental-income-tax-guide': {
        'title': 'Korean Housing Rental Income Tax: 20 Million KRW Separate vs. Comprehensive Taxation',
        'desc': 'Landlord tax guide for property rentals in Korea. 14% separate taxation for rental income under 20M KRW, official registered rental business deductions, and health insurance impact.',
        'category': 'tax',
        'catName': 'Tax & Expat Settlement',
        'tags': ['RentalIncomeTax', 'KoreaRealEstate', 'LandlordTax', 'SeparateTaxation', 'PropertyIncome'],
        'intro': 'Owners of rental real estate in Korea earning under 20 million KRW annually can choose a low 14% separate tax rate to avoid high progressive tax brackets.',
        'c1_title': 'Rental Taxation Thresholds',
        'c1_left': 'Under 20M KRW/year: Eligible for 14% separate tax (15.4% with local tax) without global income merge',
        'c1_right': 'Registered Housing Rental Business: 60% necessary expense rate + 4M KRW deduction',
    },
    'inheritance-vs-gift-tax-saving-strategy': {
        'title': 'Inheritance vs. Gift Tax in Korea: 10-Year Cycle Gifting to Save 100 Million KRW in Tax',
        'desc': 'Comparing Koreas estate tax (10-50%) and gift tax. How to utilize 10-year statutory gift exemptions (Spouse 600M, Adult Child 50M) to shield against estate tax audits.',
        'category': 'tax',
        'catName': 'Tax & Expat Settlement',
        'tags': ['InheritanceTax', 'GiftTaxKorea', 'EstatePlanning', 'TaxExemption', 'PropertyInheritance'],
        'intro': 'With rising real estate values, planning lifetime gifting on a 10-year cycle prevents massive 50% top-bracket estate taxes when assets transfer to the next generation.',
        'c1_title': '10-Year Gift Exemption Limits',
        'c1_left': 'Spouse: 600 Million KRW tax-free every 10 years (Up to 1.8B KRW over 30 years)',
        'c1_right': 'Adult Children: 50 Million KRW tax-free (Minor children 20 Million KRW)',
    },
    'irp-vs-pension-savings-comparison': {
        'title': 'IRP vs. Pension Savings vs. ISA: 9 Million KRW Tax Deduction Allocation Formula in Korea',
        'desc': 'Comparing IRP (Individual Retirement Pension), Pension Savings Fund, and ISA accounts in Korea. How to allocate 9M KRW annually to get up to 1.485M KRW tax refund.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['IRP', 'PensionSavings', 'KoreaRetirement', 'TaxCredit', 'WealthBuilding'],
        'intro': 'Maximizing your retirement accounts with 9 million KRW annually provides a guaranteed 13.2% to 16.5% tax refund while compounding in US index ETFs tax-deferred.',
        'c1_title': 'Optimal 9M KRW Account Split',
        'c1_left': 'Pension Savings Fund (6M KRW): 100% investment freedom in stock ETFs with zero cash drag',
        'c1_right': 'IRP Account (3M KRW): Reaches full 9M KRW ceiling; 30% safe asset requirement applied',
    },
    'jeonse-deposit-return-guarantee-support': {
        'title': '2026 Korea Jeonse Deposit Return Guarantee Fee Subsidy: Up to 300,000 KRW Cash Refund',
        'desc': 'Government subsidy reimbursing 100% of HUG, HF, and SGI Jeonse guarantee insurance premiums (up to 300K KRW) for young tenants and newlyweds in South Korea.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['JeonseGuarantee', 'HUGInsurance', 'HousingSupport', 'TenantRights', 'KoreaRent'],
        'intro': 'To protect tenants from losing their large rental deposits (Jeonse), the Korean government refunds up to 300,000 KRW of your guarantee insurance premium in cash.',
        'c1_title': 'Eligibility for 100% Premium Refund',
        'c1_left': 'Tenant Status: Registered tenant with HUG/HF/SGI guarantee insurance on deposit <= 300M KRW',
        'c1_right': 'Income Limits: Youth under 39 (< 50M KRW), Newlyweds (< 75M KRW combined)',
    },
    'jeonse-fraud-prevention-checklist': {
        'title': '5-Step Jeonse Fraud Prevention Checklist: Real Estate Registry, Senior Mortgages, and HUG',
        'desc': 'Essential due diligence before signing rental contracts in Korea. Reading Section A/B of the Supreme Court Registry (등기부등본), trust company fraud, and required contract clauses.',
        'category': 'credit',
        'catName': 'Banking & Credit',
        'tags': ['JeonseFraud', 'RealEstateRegistry', 'RentalContract', 'HUGGuarantee', 'ExpatHousing'],
        'intro': 'Protect your life savings when renting apartments or villas in Korea by verifying property liens, landlord tax arrears, and inserting non-negotiable protective clauses.',
        'c1_title': 'Registry Verification Rules',
        'c1_left': 'Section Gap (갑구): Verify exact owner ID; avoid any properties with Seizure or Trust flags',
        'c1_right': 'Section Eul (을구): Ensure (Senior Mortgages + Your Deposit) <= 70% of market value',
    },
    'kakaobank-vs-toss-parking-account-battle': {
        'title': 'KakaoBank vs. Toss Bank vs. Kbank: Best Digital Bank Parking Account Comparison 2026',
        'desc': 'Head-to-head comparison of Korean internet bank parking accounts. Kbank Plus Box (2.5%), Toss Bank Account, and KakaoBank Safe Box interest rates and daily compounding.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['KakaoBank', 'TossBank', 'Kbank', 'ParkingAccount', 'DailyInterest'],
        'intro': 'Which internet bank pays the best daily compound interest for emergency funds? We compare rates, deposit caps, and UI convenience across the big three.',
        'c1_title': 'Digital Bank Parking Rates',
        'c1_left': 'Kbank Plus Box: Highest 2.5% rate with up to 1 Billion KRW deposit ceiling',
        'c1_right': 'Toss Bank: Unlimited deposit cap with instant daily interest withdrawal button',
    },
    'loan-interest-rate-reduction-right': {
        'title': 'How to Exercise Your Right to Request Loan Interest Rate Reductions in Korea (1.5% Cut)',
        'desc': 'Legal rights under Article 45-2 of the Financial Consumer Protection Act. How to lower your mortgage or personal loan interest rate in Korea after credit score or salary increases.',
        'category': 'credit',
        'catName': 'Banking & Credit',
        'tags': ['InterestRateReduction', 'BankLoansKorea', 'CreditScore', 'MortgageDiscount', 'FSSKorea'],
        'intro': 'If your income or credit score has improved since taking out a loan, Korean law grants you the right to demand lower interest rates from commercial banks with zero penalty.',
        'c1_title': 'Eligible Conditions for Rate Cut',
        'c1_left': 'Salary & Career: Promotions, job transitions to larger firms, or verifiable income increases',
        'c1_right': 'Credit Rating: Significant jumps in KCB or NICE scores since initial loan origination',
    },
    'loan-prepayment-penalty-exemption': {
        'title': 'Korean Loan Prepayment Penalty Exemptions & Refinancing Guide',
        'desc': 'When banks must waive the 1.2%~1.4% early repayment fee in Korea. 3-year statutory expiration rule, policy loans, and online refinancing platforms (대환대출).',
        'category': 'credit',
        'catName': 'Banking & Credit',
        'tags': ['PrepaymentPenalty', 'LoanRefinancing', 'MortgageKorea', 'BankFees', 'DebtManagement'],
        'intro': 'Paying off bank loans early usually incurs a 1.2% to 1.4% fee. Knowing when the fee expires after 3 years saves millions of KRW when refinancing to lower interest rates.',
        'c1_title': 'Prepayment Rules in Korea',
        'c1_left': '3-Year Statutory Expiry: Prepayment fees drop to 0% after exactly 3 years from origination',
        'c1_right': 'Online Refinancing: Move existing credit and housing loans to lower rates via mobile apps',
    },
    'minus-bankbook-dsr-limit-guide': {
        'title': 'Minus Bankbook (Overdraft Account) DSR Calculation Rules & Limit Management in Korea',
        'desc': 'How overdraft credit lines (마이너스통장) impact your Debt Service Ratio (DSR) in South Korea. Unused limits, interest calculation, and mortgage loan eligibility.',
        'category': 'credit',
        'catName': 'Banking & Credit',
        'tags': ['MinusBankbook', 'DSRKorea', 'OverdraftAccount', 'CreditLine', 'MortgageLimit'],
        'intro': 'Even if you never withdraw money from your overdraft account, banks calculate your entire approved limit against your DSR debt capacity when applying for mortgages.',
        'c1_title': 'DSR Calculation Rules',
        'c1_left': 'Unused Limit Impact: 100% of approved overdraft limit counts as existing debt in DSR',
        'c1_right': 'Interest Formula: Daily interest is only charged on the exact negative balance utilized',
    },
    'newborn-special-mortgage-loan-2026': {
        'title': '2026 Korea Newborn Special Mortgage & Jeonse Loan: 1% Interest Rate & DSR Exemption',
        'desc': 'Government subsidized housing loans for parents with children born within 2 years in Korea. 1.6%~3.3% ultra-low mortgage rate, 500M KRW loan limit, and DSR exemption rules.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['NewbornSpecialLoan', 'KoreaMortgage', 'HousingSupport', 'LowInterestLoan', 'ParentingSubsidy'],
        'intro': 'Parents with babies born within the past 2 years can purchase homes valued up to 900M KRW with 1% range mortgage rates while being exempt from restrictive DSR caps.',
        'c1_title': 'Newborn Special Loan Highlights',
        'c1_left': 'Mortgage Rate: 1.6% ~ 3.3% fixed for 5 years (Up to 500M KRW loan limit)',
        'c1_right': 'Income Ceiling: Combined household annual income up to 130M KRW (relaxed to 200M KRW)',
    },
    'overseas-stock-capital-gains-tax': {
        'title': '2026 Overseas Stock (US Equities) Capital Gains Tax in Korea: 2.5M KRW Exemption Guide',
        'desc': 'How Korean residents and expats are taxed on US stock capital gains. 22% flat tax, 2.5M KRW annual basic exemption, profit-loss aggregation, and May filing requirements.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['USStocksTax', 'CapitalGainsKorea', 'StockTaxFiling', 'Hometax', 'OverseasTrading'],
        'intro': 'Trading US stocks like Apple and Tesla in Korea is subject to a 22% tax on annual net profits exceeding 2.5 million KRW. Utilizing loss offsetting minimizes your final tax bill.',
        'c1_title': '22% Capital Gains Rules',
        'c1_left': 'Annual Exemption: First 2.5 Million KRW in net capital gains is 100% tax-free each year',
        'c1_right': 'Loss Aggregation: Losses on Stock B offset gains on Stock A within the same calendar year',
    },
    'raise-credit-score-to-900': {
        'title': '7 Actionable Steps to Raise Your Korean Credit Score to 900+ (KCB & NICE)',
        'desc': 'Master guide to boosting your credit rating in South Korea. Credit card utilization below 30%, non-financial data submission (utility/telecom bills), and avoiding revolving credit.',
        'category': 'credit',
        'catName': 'Banking & Credit',
        'tags': ['CreditScoreKorea', 'KCB', 'NICE', 'CreditCardUsage', 'LoanInterestDiscount'],
        'intro': 'A credit score in the 900s saves tens of millions of KRW in loan interest over your lifetime. Follow these 7 proven rules to climb from 700 to 950+ tier.',
        'c1_title': 'Core Credit Boosting Rules',
        'c1_left': 'Card Utilization: Keep monthly spending under 30% of your total approved credit limit',
        'c1_right': 'Instant Points Boost: Submit telecom and health insurance payment records via mobile banking apps',
    },
    'schd-us-dividend-etf-tax-strategy': {
        'title': 'US Dividend ETF (SCHD & JEPI) Tax Optimization Guide in Korea: 0% Tax Strategy',
        'desc': 'How to invest in US dividend ETFs in Korea without 15.4% dividend tax. Utilizing ISA and Pension Savings accounts to defer taxes and maximize monthly compound dividends.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['SCHD', 'JEPI', 'DividendTaxKorea', 'ISAAccount', 'PassiveIncome'],
        'intro': 'Holding high-dividend US ETFs in standard accounts triggers 15.4% tax and global financial income risks. Holding domestic versions in ISA accounts keeps taxes near zero.',
        'c1_title': 'Tax Sheltered Dividend Strategy',
        'c1_left': 'ISA Account: Up to 5M KRW in dividends 100% tax-free, 9.9% separate tax on excess',
        'c1_right': 'Pension Account: 0% tax during accumulation; low 3.3%~5.5% pension income tax upon retirement',
    },
    'severance-pay-tax-saving-irp': {
        'title': 'Korean Severance Pay (퇴직금) Retirement Income Tax & IRP 30-40% Tax Reduction Guide',
        'desc': 'How retirement income tax is calculated in Korea. Continuous service deduction benefits and rolling over severance pay to an IRP account for 30%~40% permanent tax cuts.',
        'category': 'tax',
        'catName': 'Tax & Expat Settlement',
        'tags': ['SeverancePayKorea', 'RetirementTax', 'IRPRollover', 'PensionsKorea', 'ExpatSeverance'],
        'intro': 'Rolling your severance pay (퇴직금) directly into an IRP account defers 100% of your severance tax and reduces your ultimate retirement tax bill by 30% to 40%.',
        'c1_title': 'IRP Severance Tax Savings',
        'c1_left': 'Immediate Tax Deferral: 100% of severance principal arrives in IRP with zero tax withheld',
        'c1_right': 'Pension Withdrawal: Pay only 70% of tax during years 1-10, and 60% of tax after year 11',
    },
    'small-business-refinance-loan': {
        'title': 'Korea Small Business Low-Interest Refinancing Loan: 4.5% Cap on High-Interest Debt',
        'desc': 'Government debt relief program helping small business owners and self-employed individuals convert 7%+ high-interest loans into 4.5% subsidized long-term installment loans.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['SmallBusinessKorea', 'RefinancingLoan', 'SelfEmployed', 'DebtRelief', 'KoreaBusiness'],
        'intro': 'Small business owners with high-interest loans (7%+) can refinance up to 100 million KRW into a 4.5% subsidized installment loan through the Korea Credit Guarantee Foundation.',
        'c1_title': 'Refinancing Program Terms',
        'c1_left': 'Target Debt: Non-bank loans with interest rates of 7% or higher taken out by active businesses',
        'c1_right': 'Refinanced Terms: Fixed/Subsidized 4.5% rate with 10-year installment repayment',
    },
    'sp500-vs-nasdaq100-longterm-strategy': {
        'title': 'S&P 500 vs. NASDAQ-100 ETF 20-Year Compound Growth Backtesting & Portfolio Strategy',
        'desc': 'Detailed 20-year backtesting comparison of S&P 500 (VOO/SPY) and NASDAQ-100 (QQQ). Compound returns, maximum drawdowns, and dollar-cost averaging in Korean tax-sheltered accounts.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['SP500', 'Nasdaq100', 'USIndexInvesting', 'CompoundInterest', 'LongTermInvesting'],
        'intro': 'Warren Buffett recommends index funds for 90% of long-term wealth. We analyze 20 years of data comparing the S&P 500 and tech-heavy NASDAQ-100 for retail investors.',
        'c1_title': '20-Year DCA Simulation (500K KRW/Month)',
        'c1_left': 'S&P 500 (10% CAGR): 120M KRW invested grows to approx. 380 Million KRW (3.1x)',
        'c1_right': 'NASDAQ-100 (15% CAGR): 120M KRW invested grows to approx. 750 Million KRW (6.2x)',
    },
    'stepping-stone-vs-stepping-loan-guide': {
        'title': 'Didimdol Mortgage Loan vs. Beotimok Jeonse Loan: 2026 Korea Housing Policy Loan Comparison',
        'desc': 'Comparing Koreas premier government housing loans. Didimdol (home purchase mortgage at 2%~3%) vs. Beotimok (jeonse rental loan at 1%~2%), income limits, and application steps.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['DidimdolLoan', 'BeotimokLoan', 'KoreaHousing', 'PolicyMortgage', 'FirstTimeHomebuyer'],
        'intro': 'Didimdol (for purchasing homes) and Beotimok (for renting Jeonse) offer the lowest fixed interest rates in South Korea backed by the Housing and Urban Guarantee Corporation.',
        'c1_title': 'Didimdol vs Beotimok Core Comparison',
        'c1_left': 'Didimdol (Home Purchase): Rates 2.45%~3.55%, up to 400M KRW for homes <= 500M KRW',
        'c1_right': 'Beotimok (Jeonse Rental): Rates 1.5%~2.7%, up to 300M KRW for deposits <= 300M KRW',
    },
    'tomorrow-learning-card-5million-guide': {
        'title': 'Korea National Tomorrow Learning Card: Up to 5 Million KRW Vocational Training Subsidy',
        'desc': 'Ministry of Employment and Labor (MOEL) training card guide. 3M~5M KRW government grants for coding, AI, accounting, and job certifications for employees and jobseekers.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['TomorrowLearningCard', 'MOELKorea', 'VocationalTraining', 'FreeCodingBootcamp', 'CareerGrowth'],
        'intro': 'Anyone residing in Korea (employees, jobseekers, freelancers) can receive 3 to 5 million KRW in government subsidies to study coding, AI, languages, or professional certifications.',
        'c1_title': 'Learning Card Subsidy Highlights',
        'c1_left': 'Standard Grant: 3,000,000 KRW baseline funding over a 5-year period for course fees',
        'c1_right': 'K-Digital Training: 100% full government tuition coverage + monthly living stipend',
    },
    'treasury-bond-investment-guide': {
        'title': 'Korean Treasury Bonds for Individual Investors vs. US Short-Term Treasury ETFs',
        'desc': 'Ministry of Economy and Finance retail treasury bond guide. 10-year/20-year compound interest yields, 14% separate taxation, and US short-term Treasury ETF (SGOV) dollar parking.',
        'category': 'wealth',
        'catName': 'Wealth & Invest',
        'tags': ['KoreanTreasuryBonds', 'RetailBonds', 'SGOV', 'SeparateTaxation', 'SafeInvesting'],
        'intro': 'For conservative investors seeking higher yields than bank deposits with 100% government safety, retail Treasury bonds offer compound interest and separate tax shields.',
        'c1_title': 'Individual Treasury Bond Perks',
        'c1_left': 'Annual Compound Yield: Holding 10/20-year bonds to maturity compounds interest annually',
        'c1_right': '14% Separate Tax: Taxed separately up to 200M KRW; excluded from global financial tax',
    },
    'youth-future-savings-vs-jump-account': {
        'title': '2026 Korea Youth Leap Account (청년도약계좌): 50 Million KRW Asset Building Guide',
        'desc': 'Government-backed savings account for young adults in Korea. 5-year maturity, government matching contributions up to 6%, 100% tax-free interest, and maturity yield calculation.',
        'category': 'subsidy',
        'catName': 'Subsidies & Living',
        'tags': ['YouthLeapAccount', 'KoreaYouthSavings', 'TaxFreeSavings', 'AssetBuilding', 'WealthCreation'],
        'intro': 'By saving up to 700,000 KRW monthly for 5 years, young adults in Korea receive government matching grants and tax-free interest to accumulate over 50,000,000 KRW.',
        'c1_title': 'Youth Leap Account Benefits',
        'c1_left': 'Government Matching: Up to 24,000~33,000 KRW monthly subsidy added directly to your balance',
        'c1_right': '100% Tax-Free: 0% tax on all accrued interest upon 5-year maturity completion',
    }
}

count = 0
for kr_slug, data in kr_to_en.items():
    en_slug = f'en-{kr_slug}.mdx'
    fpath = os.path.join(blog_dir, en_slug)
    if os.path.exists(fpath):
        continue
    
    tags_str = '["' + '", "'.join(data['tags']) + '"]'
    
    lines = [
        '---',
        f'title: "{data["title"]}"',
        f'description: "{data["desc"]}"',
        'pubDate: 2026-05-01',
        f'category: "{data["category"]}"',
        f'categoryName: "{data["catName"]}"',
        f'tags: {tags_str}',
        'author: "MegaMoneyMomentum Global Editorial Team"',
        'featured: false',
        'readingTime: "6 min"',
        'officialSources:',
        '  - name: "National Tax Service / Ministry of Economy and Finance Korea"',
        '    url: "https://www.nts.go.kr/english"',
        '---',
        '',
        "import InfographicCard from '../../components/InfographicCard.astro';",
        "import StepFlow from '../../components/StepFlow.astro';",
        '',
        data['intro'],
        '',
        'Navigating personal finance, taxation, and government programs in South Korea can feel complex, but understanding the foundational rules allows you to maximize statutory benefits and protect your hard-earned wealth.',
        '',
        '---',
        '',
        '## 1. Key Highlights & Eligibility Overview',
        '',
        f'<InfographicCard title="{data["c1_title"]}" type="primary" subtitle="Official Government Regulatory Standards">',
        '  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">',
        '    <div style="background: var(--bg-main); padding: 1rem; border-radius: var(--radius-sm); border: 1px solid var(--border-color);">',
        '      <h4 style="color: var(--primary); margin-bottom: 0.5rem;">📌 Primary Requirements</h4>',
        f'      <p style="font-size: 0.85rem; margin: 0; line-height: 1.5;">{data["c1_left"]}</p>',
        '    </div>',
        '    <div style="background: var(--bg-main); padding: 1rem; border-radius: var(--radius-sm); border: 1px solid var(--border-color);">',
        '      <h4 style="color: var(--secondary); margin-bottom: 0.5rem;">💡 Key Financial Takeaway</h4>',
        f'      <p style="font-size: 0.85rem; margin: 0; line-height: 1.5;">{data["c1_right"]}</p>',
        '    </div>',
        '  </div>',
        '</InfographicCard>',
        '',
        '---',
        '',
        '## 2. Step-by-Step Practical Application Process',
        '',
        '<StepFlow',
        '  steps={[',
        '    { num: "1", title: "Verify Eligibility Criteria", desc: "Check your Alien Registration status, income bracket, and requisite documents.", icon: "📋" },',
        '    { num: "2", title: "Access Official Portal", desc: "Log into the relevant ministry or banking app using simple mobile authentication.", icon: "💻" },',
        '    { num: "3", title: "Submit & Track Application", desc: "Upload required certificates and confirm direct deposit or tax adjustment.", icon: "✅" },',
        '  ]}',
        '/>',
        '',
        '---',
        '',
        '## 3. Editorial Insights & Crucial Tips',
        '',
        '- **Check Deadlines:** Missing official submission windows can forfeit retroactive claims, so set calendar reminders early.',
        '- **Maintain Documentation:** Keep digital copies of bank wire receipts, certificates of employment, and lease agreements safely archived.',
        '',
        '---',
        '',
        '> 🔗 **Related Financial Guides in English**:',
        '> - [2026 Korea Year-End Tax Settlement Guide for Foreign Workers](/blog/korea-tax-settlement-guide-foreigners-2026)',
        '> - [How Foreigners and Expats Can Open Bank Accounts in Korea](/blog/open-korea-bank-account-for-expats)',
        ''
    ]
    
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'Successfully created: {en_slug}')
    count += 1

print(f'Total English posts generated: {count}')
